import TextContent from '@/components/TextContent'
import TitlePage from '@/components/TitlePage'
import Head from 'next/head'
import Layout from '../components/Layout'

export default function About() {
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <TitlePage title="About Me" />
        <TextContent className='border-b border-b-gray-300'>Saya Ahmad, seorang <b>Fullstack Web Developer</b>, dan saya senang dapat berbagi karya dan pengalaman saya dengan anda disini.</TextContent>
        <TextContent>Sebagai seorang software engineer, saya telah mengembangkan berbagai aplikasi dan platform yang melibatkan teknologi canggih seperti Java, Python, dan React Native. Saya selalu mencari cara untuk meningkatkan keterampilan saya dan mengeksplorasi teknologi baru yang dapat membantu saya menciptakan solusi yang lebih baik.</TextContent>
        <TextContent>Saya percaya bahwa pengembangan perangkat lunak bukan hanya tentang menulis kode, tetapi juga tentang memahami kebutuhan pengguna dan memastikan pengalaman pengguna yang optimal. Dengan itu, saya selalu berusaha untuk memahami konteks bisnis yang mendukung produk yang saya buat dan mengoptimalkan solusi yang dapat memberikan dampak positif bagi bisnis dan pengguna. Saya senang berbagi pengalaman saya dalam mengembangkan perangkat lunak dan memberikan solusi teknologi yang inovatif.</TextContent>
        <TextContent>Silakan jelajahi portofolio saya dan jangan ragu untuk menghubungi saya jika Anda tertarik untuk bekerja sama atau berdiskusi lebih lanjut tentang proyek Anda. Terima kasih telah mengunjungi halaman saya!</TextContent>
      </Layout>
    </>
  )
}
