import BlogCard from '@/components/BlogCard'
import TitlePage from '@/components/TitlePage'
import Head from 'next/head'
import Layout from '../components/Layout'

export default function About() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <TitlePage title="Blog" />
        <BlogCard />
        <BlogCard />
        <BlogCard />
        <BlogCard />
        <BlogCard />
      </Layout>
    </>
  )
}