import GuestBookCard from '@/components/GuestBookCard'
import TitlePage from '@/components/TitlePage'
import Head from 'next/head'
import Layout from '../components/Layout'
import GuestBookButton from '@/components/GuestBookButton'
import { useState } from 'react'
import GuestBookInput from '@/components/GuestBookInput'

interface IGuestBooks {
    username: string,
    message: string
}

export default function GuestBook() {
    let [loggedIn, setLoggedIn] = useState(false)
    let [guestBooks, setGuestBooks] = useState<IGuestBooks[]>([])

    return (
        <>
            <Head>
                <title>Guest Books</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <TitlePage title="Guest Book" />
                {loggedIn ? <GuestBookInput onclick={() => setLoggedIn(false)} /> : <GuestBookButton onclick={() => setLoggedIn(true)} /> }
                {guestBooks.length > 0 && <GuestBookCard />}
            </Layout>
        </>
    )
}